buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
        classpath 'com.google.gms:google-services:4.3.10'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

repositories {
    google()
    mavenCentral()
    maven { url "https://jitpack.io" }
}

android {
    compileSdkVersion 32
    defaultConfig {
        applicationId "com.pinmyballs"
        vectorDrawables.useSupportLibrary = true
        minSdkVersion 19
        targetSdkVersion 32
        versionCode 64
        versionName "3.23"
        buildConfigField('String', 'ApiKey', PinMyBalls_GoogleMapAPIKey)
        resValue('string', 'maps_api_key', PinMyBalls_GoogleMapAPIKey)
        multiDexEnabled = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            buildConfigField 'String', 'ApiKey', PinMyBalls_GoogleMapAPIKey
            resValue 'string', 'api_key', PinMyBalls_GoogleMapAPIKey
        }
    }
    buildFeatures {
        viewBinding true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace 'com.pinmyballs'
}

dependencies {
    implementation 'com.google.android.material:material:1.7.0-alpha01'
    implementation 'com.google.android.libraries.places:places:2.6.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'com.google.android.gms:play-services-maps:18.0.2'
    implementation 'com.google.android.gms:play-services-location:19.0.1'
    implementation 'com.google.android.gms:play-services-places:17.0.0'
    implementation 'com.google.maps.android:android-maps-utils:2.3.0'
    implementation 'com.google.code.gson:gson:2.9.0'
    implementation 'com.github.parse-community.Parse-SDK-Android:parse:1.25.0'
    implementation 'com.jakewharton:butterknife:10.2.3'
    annotationProcessor 'com.jakewharton:butterknife-compiler:10.2.3'
    implementation 'org.parceler:parceler-api:1.1.13'
    annotationProcessor 'org.parceler:parceler:1.1.13'
    implementation 'joda-time:joda-time:2.10.14'
//    implementation 'com.github.ittianyu:BottomNavigationViewEx:2.0.4'
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'com.makeramen:roundedimageview:2.3.0'

    //Analytics with Firebase
    implementation platform('com.google.firebase:firebase-bom:30.0.2')
    implementation 'com.google.firebase:firebase-analytics'

    //old way ?
    implementation 'com.google.android.gms:play-services-analytics:18.0.1'
}
